"""Initialize re-desgined schemas

Revision ID: 536865fdd9ba
Revises: 
Create Date: 2025-06-17 18:43:38.262027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536865fdd9ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_description', sa.Text(), nullable=False),
    sa.Column('pod_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_node_id'), 'alerts', ['node_id'], unique=False)
    op.create_index(op.f('ix_alerts_pod_id'), 'alerts', ['pod_id'], unique=False)
    op.create_table('pod_request_decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pod_id', sa.UUID(), nullable=False),
    sa.Column('pod_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('is_elastic', sa.Boolean(), nullable=False),
    sa.Column('queue_name', sa.String(length=255), nullable=False),
    sa.Column('demand_cpu', sa.Float(), nullable=False),
    sa.Column('demand_memory', sa.Float(), nullable=False),
    sa.Column('demand_slack_cpu', sa.Float(), nullable=True),
    sa.Column('demand_slack_memory', sa.Float(), nullable=True),
    sa.Column('is_decision_status', sa.Boolean(), nullable=False),
    sa.Column('pod_parent_id', sa.UUID(), nullable=False),
    sa.Column('pod_parent_kind', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuning_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('output_1', sa.Float(), nullable=False),
    sa.Column('output_2', sa.Float(), nullable=False),
    sa.Column('output_3', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuning_parameters_id'), 'tuning_parameters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tuning_parameters_id'), table_name='tuning_parameters')
    op.drop_table('tuning_parameters')
    op.drop_table('pod_request_decision')
    op.drop_index(op.f('ix_alerts_pod_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_node_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
