"""add extra field to alert table

Revision ID: 56c6519f404b
Revises: 0af4db42c33f
Create Date: 2025-07-08 18:09:12.408467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c6519f404b'
down_revision: Union[str, None] = '0af4db42c33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable
    op.add_column('workload_request_decision', sa.Column('pod_parent_name', sa.String(length=255), nullable=True))
    # Step 2: Fill existing rows
    op.execute("UPDATE workload_request_decision SET pod_parent_name = 'unknown'")
    # Step 3: Alter column to be NOT NULL
    op.alter_column('workload_request_decision', 'pod_parent_name', nullable=False)
    # Step 1: Add column as nullable
    op.add_column('alerts', sa.Column('alert_model', sa.Text(), nullable=True))
    # Step 2: Fill existing rows
    op.execute("UPDATE alerts SET alert_model = 'unknown'")
    # Step 3: Alter column to be NOT NULL
    op.alter_column('alerts', sa.Column('alert_model', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workload_request_decision', 'pod_parent_name')
    op.drop_column('alerts', 'alert_model')
    # ### end Alembic commands ###
