"""upToDate

Revision ID: 0edd8063a604
Revises: cae99e0d2958
Create Date: 2025-05-25 13:20:29.520360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0edd8063a604'
down_revision: Union[str, None] = 'cae99e0d2958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('node', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('pod', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('pod', 'namespace',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tuning_parameters', 'output_1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tuning_parameters', 'output_2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tuning_parameters', 'output_3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tuning_parameters', 'alpha',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tuning_parameters', 'beta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tuning_parameters', 'gamma',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_tuning_parameters_id'), 'tuning_parameters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tuning_parameters_id'), table_name='tuning_parameters')
    op.alter_column('tuning_parameters', 'gamma',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tuning_parameters', 'beta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tuning_parameters', 'alpha',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tuning_parameters', 'output_3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tuning_parameters', 'output_2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tuning_parameters', 'output_1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pod', 'namespace',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pod', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('node', 'location')
    op.drop_column('node', 'ip_address')
    # ### end Alembic commands ###
