"""Rename pod request decision to workload decision

Revision ID: 9f5ab71e4ed1
Revises: 78030ce8df1b
Create Date: 2025-06-24 10:32:25.232438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f5ab71e4ed1'
down_revision: Union[str, None] = '78030ce8df1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workload_decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pod_id', sa.UUID(), nullable=False),
    sa.Column('pod_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('is_elastic', sa.Boolean(), nullable=False),
    sa.Column('queue_name', sa.String(length=255), nullable=False),
    sa.Column('demand_cpu', sa.Float(), nullable=False),
    sa.Column('demand_memory', sa.Float(), nullable=False),
    sa.Column('demand_slack_cpu', sa.Float(), nullable=True),
    sa.Column('demand_slack_memory', sa.Float(), nullable=True),
    sa.Column('is_decision_status', sa.Boolean(), nullable=False),
    sa.Column('pod_parent_id', sa.UUID(), nullable=False),
    sa.Column('pod_parent_kind', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pod_request_decision')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pod_request_decision',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pod_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pod_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('namespace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_elastic', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('queue_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('demand_cpu', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('demand_memory', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('demand_slack_cpu', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('demand_slack_memory', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_decision_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pod_parent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pod_parent_kind', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pod_request_decision_pkey')
    )
    op.drop_table('workload_decision')
    # ### end Alembic commands ###
