"""Status field to workload-request

Revision ID: 6ec92e9d685b
Revises: 0edd8063a604
Create Date: 2025-05-27 17:10:03.132895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec92e9d685b'
down_revision: Union[str, None] = '0edd8063a604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload_request', sa.Column('status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workload_request', 'status')
    # ### end Alembic commands ###
