"""Make is_decision_status default value to None

Revision ID: aaa66689a4fe
Revises: 586945147dca
Create Date: 2025-07-25 18:59:52.494566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa66689a4fe'
down_revision: Union[str, None] = '586945147dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workload_request_decision', 'is_decision_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workload_request_decision', 'is_decision_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
