"""Replace workload_request_id with pod_id in workload_request_decision

Revision ID: 4283438e660a
Revises: 51b124187042
Create Date: 2025-05-30 09:39:16.001483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4283438e660a'
down_revision: Union[str, None] = '51b124187042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload_request_decision', sa.Column('pod_id', sa.UUID(), nullable=False))
    op.drop_constraint('workload_request_decision_workload_request_id_fkey', 'workload_request_decision', type_='foreignkey')
    op.create_foreign_key(None, 'workload_request_decision', 'pod', ['pod_id'], ['id'])
    op.drop_column('workload_request_decision', 'workload_request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload_request_decision', sa.Column('workload_request_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workload_request_decision', type_='foreignkey')
    op.create_foreign_key('workload_request_decision_workload_request_id_fkey', 'workload_request_decision', 'workload_request', ['workload_request_id'], ['id'])
    op.drop_column('workload_request_decision', 'pod_id')
    # ### end Alembic commands ###
