"""asdfadsf

Revision ID: 60b2e03bc996
Revises: 2f4fda3d071b
Create Date: 2025-08-07 16:43:27.475288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b2e03bc996'
down_revision: Union[str, None] = '2f4fda3d071b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload_request_decision', sa.Column('action_type', sa.Enum('bind', 'create', 'delete', 'move', 'swap_x', 'swap_y', name='workload_action_type_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workload_request_decision', 'action_type')
    # ### end Alembic commands ###
