"""Include action_type in workload_request_decision table

Revision ID: 71bbf011e6bb
Revises: 2f4fda3d071b
Create Date: 2025-08-06 21:24:34.380604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bbf011e6bb'
down_revision: Union[str, None] = '2f4fda3d071b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload_request_decision', sa.Column('action_type', sa.Enum('bind', 'create', 'delete', 'move', 'swap_x', 'swap_y', name='workload_action_type_enum'), nullable=True))
    op.execute("UPDATE workload_request_decision SET action_type = 'create' WHERE action_type IS NULL")
    op.alter_column('workload_request_decision', 'action_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workload_request_decision', 'action_type')
    # ### end Alembic commands ###
