"""Add duration colum to the request and action tables

Revision ID: cb263572c114
Revises: 71bbf011e6bb
Create Date: 2025-09-11 16:44:11.754097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb263572c114'
down_revision: Union[str, None] = '71bbf011e6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload_action', sa.Column('durationInSeconds', sa.String(), nullable=True))
    op.add_column('workload_request_decision', sa.Column('durationInSeconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workload_request_decision', 'durationInSeconds')
    op.drop_column('workload_action', 'durationInSeconds')
    # ### end Alembic commands ###
