"""Delete durationInSec field and add start and end timestamps

Revision ID: cef3654218e2
Revises: cb263572c114
Create Date: 2025-09-17 00:49:34.724547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef3654218e2'
down_revision: Union[str, None] = 'cb263572c114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable with default
    op.add_column('workload_request_decision', sa.Column('decision_start_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('workload_request_decision', sa.Column('decision_end_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # Update all existing rows (optional if using server_default)
    op.execute("UPDATE workload_request_decision SET decision_start_time = now() WHERE decision_start_time IS NULL")
    op.execute("UPDATE workload_request_decision SET decision_end_time = now() WHERE decision_end_time IS NULL")
    # Alter to NOT NULL
    op.alter_column('workload_request_decision', 'decision_start_time', nullable=False)
    op.alter_column('workload_request_decision', 'decision_end_time', nullable=False)
    # Remove server_default if you don't want it for future inserts
    op.alter_column('workload_request_decision', 'decision_start_time', server_default=None)
    op.alter_column('workload_request_decision', 'decision_end_time', server_default=None)
    # Drop old column
    op.drop_column('workload_request_decision', 'durationInSeconds')
    op.drop_column('workload_action', 'durationInSeconds')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload_request_decision', sa.Column('durationInSeconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('workload_request_decision', 'decision_end_time')
    op.drop_column('workload_request_decision', 'decision_start_time')
    op.add_column('workload_action', sa.Column('durationInSeconds', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
