"""Add workload_timing table

Revision ID: 56c880d2bb62
Revises: 4d52a561097f
Create Date: 2025-10-07 18:00:08.664646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c880d2bb62'
down_revision: Union[str, None] = '4d52a561097f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workload_timing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pod_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=True),
    sa.Column('scheduler_type', sa.Enum('SCHEDULER_DEFAULT', 'SCHEDULER_RMS', name='workload_timing_scheduler_enum'), nullable=False),
    sa.Column('pod_uid', sa.String(length=255), nullable=False),
    sa.Column('created_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scheduled_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ready_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('creation_to_scheduled_ms', sa.Double(), nullable=True),
    sa.Column('scheduled_to_ready_ms', sa.Double(), nullable=True),
    sa.Column('creation_to_ready_ms', sa.Double(), nullable=True),
    sa.Column('total_lifecycle_ms', sa.Double(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workload_timing')
    # ### end Alembic commands ###
