"""add pod_name and node_name to alerts

Revision ID: 4a5ffcff687b
Revises: 56c880d2bb62
Create Date: 2025-10-15 15:13:29.825293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5ffcff687b'
down_revision: Union[str, None] = '56c880d2bb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('pod_name', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('node_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'node_name')
    op.drop_column('alerts', 'pod_name')
    # ### end Alembic commands ###
