"""Add placement_decision table

Revision ID: f9d64a71a1ad
Revises: 4a5ffcff687b
Create Date: 2025-10-20 14:15:50.486546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9d64a71a1ad'
down_revision: Union[str, None] = '4a5ffcff687b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_decision',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_placement_lst', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('decision_reason', sa.String(), nullable=False),
    sa.Column('trace', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_placement_decision_decision_id'), 'placement_decision', ['decision_id'], unique=False)
    op.create_index(op.f('ix_placement_decision_name'), 'placement_decision', ['name'], unique=False)
    op.create_index(op.f('ix_placement_decision_namespace'), 'placement_decision', ['namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placement_decision_namespace'), table_name='placement_decision')
    op.drop_index(op.f('ix_placement_decision_name'), table_name='placement_decision')
    op.drop_index(op.f('ix_placement_decision_decision_id'), table_name='placement_decision')
    op.drop_table('placement_decision')
    # ### end Alembic commands ###
