"""Add kpi_metrics table

Revision ID: 422d8cbf1539
Revises: f9d64a71a1ad
Create Date: 2025-10-24 13:18:14.609271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422d8cbf1539'
down_revision: Union[str, None] = 'f9d64a71a1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_name', sa.String(length=1024), nullable=False),
    sa.Column('cpu_utilization', sa.Double(), nullable=True),
    sa.Column('mem_utilization', sa.Double(), nullable=True),
    sa.Column('decision_time_in_seconds', sa.Double(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_metrics')
    # ### end Alembic commands ###
