"""Add alert_level to the alert schema

Revision ID: 5af6b55080ea
Revises: 422d8cbf1539
Create Date: 2025-10-28 23:51:18.519348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af6b55080ea'
down_revision: Union[str, None] = '422d8cbf1539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column nullable first
    op.add_column(
        "alerts",
        sa.Column("alert_level", sa.String(length=20), nullable=True),
    )
    # 2. Backfill existing rows (choose default business value)
    op.execute("UPDATE alerts SET alert_level = 'Warning' WHERE alert_level IS NULL")
    # 3. Enforce NOT NULL
    op.alter_column("alerts", "alert_level", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'alert_level')
    # ### end Alembic commands ###
