"""Modify the KPI metrics table with new fields

Revision ID: 95259fc5e114
Revises: 5af6b55080ea
Create Date: 2025-10-31 01:57:20.969420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95259fc5e114'
down_revision: Union[str, None] = '5af6b55080ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_metrics', sa.Column('request_decision_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_metrics', 'request_decision_id')
    # ### end Alembic commands ###
