"""Create Index for KPI metrics and tuning parameters

Revision ID: 6a83507194b9
Revises: 3cd7bd1c74c5
Create Date: 2025-11-18 13:46:14.141418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a83507194b9'
down_revision: Union[str, None] = '3cd7bd1c74c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_kpi_metrics_created_at'), 'kpi_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_tuning_parameters_created_at'), 'tuning_parameters', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tuning_parameters_created_at'), table_name='tuning_parameters')
    op.drop_index(op.f('ix_kpi_metrics_created_at'), table_name='kpi_metrics')
    # ### end Alembic commands ###
