"""Make pod parent fields to nullable in workload_request_decision

Revision ID: 08e8a554b2e9
Revises: 89150dad1bc1
Create Date: 2025-12-09 11:41:36.623730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08e8a554b2e9'
down_revision: Union[str, None] = '89150dad1bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workload_request_decision', 'pod_parent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('workload_request_decision', 'pod_parent_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('workload_request_decision', 'pod_parent_kind',
               existing_type=postgresql.ENUM('deployment', 'statefulset', 'replicaset', 'job', 'daemonset', 'cronjob', name='pod_parent_type_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 0) Make existing data compatible: fill NULLs and map non-legacy enum values.
    # Choose a stable placeholder UUID for missing parent_id.
    op.execute("""
        UPDATE workload_request_decision
        SET pod_parent_id = COALESCE(pod_parent_id, '00000000-0000-0000-0000-000000000000'::uuid),
            pod_parent_name = COALESCE(pod_parent_name, 'unknown'),
            pod_parent_kind = COALESCE(pod_parent_kind, 'deployment')
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workload_request_decision', 'pod_parent_kind',
               existing_type=postgresql.ENUM('deployment', 'statefulset', 'replicaset', 'job', 'daemonset', 'cronjob', name='pod_parent_type_enum'),
               nullable=False)
    op.alter_column('workload_request_decision', 'pod_parent_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('workload_request_decision', 'pod_parent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
