"""intialize

Revision ID: 5b0ff9567a6b
Revises: 
Create Date: 2025-05-23 17:15:00.175222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0ff9567a6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('cpu_capacity', sa.Float(), nullable=False),
    sa.Column('memory_capacity', sa.Float(), nullable=False),
    sa.Column('current_cpu_assignment', sa.Float(), nullable=True),
    sa.Column('current_memory_assignment', sa.Float(), nullable=True),
    sa.Column('current_cpu_utilization', sa.Float(), nullable=True),
    sa.Column('current_memory_utilization', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuning_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('output_1', sa.Float(), nullable=False),
    sa.Column('output_2', sa.Float(), nullable=False),
    sa.Column('output_3', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuning_parameters_id'), 'tuning_parameters', ['id'], unique=False)
    op.create_table('workload_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('api_version', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('current_scale', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pod',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('demand_cpu', sa.Float(), nullable=False),
    sa.Column('demand_memory', sa.Float(), nullable=False),
    sa.Column('demand_slack_cpu', sa.Float(), nullable=True),
    sa.Column('demand_slack_memory', sa.Float(), nullable=True),
    sa.Column('is_elastic', sa.Boolean(), nullable=False),
    sa.Column('assigned_node_id', sa.Integer(), nullable=True),
    sa.Column('workload_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['workload_request_id'], ['workload_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workload_request_decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workload_request_id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('queue_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['workload_request_id'], ['workload_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workload_request_decision')
    op.drop_table('pod')
    op.drop_table('workload_request')
    op.drop_index(op.f('ix_tuning_parameters_id'), table_name='tuning_parameters')
    op.drop_table('tuning_parameters')
    op.drop_table('node')
    # ### end Alembic commands ###
