---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.app.roleName }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "componentstatuses", "namespaces", "configmaps"]
  verbs: ["list", "get"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["list", "get"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "get"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.app.roleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.app.roleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
