---
# This workflow builds and deploys 
# the Orchestration API Docker image to Docker Hub
# and deploys it to a Kubernetes cluster using Helm.

name: Build and Deploy the Orchestration API

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.set-repo-path.outputs.repo-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set repo path output
        id: set-repo-path
        run: echo "repo-path=${GITHUB_WORKSPACE}" >> $GITHUB_OUTPUT

  validate:
    name: Validate Python and YAML files
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install flake8
        run: pip install flake8

      - name: Lint Python files
        run: flake8 app/ tests/

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Lint Helm chart
        run: helm lint charts/orchestration-api

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      image_name: ${{ steps.set-image.outputs.image_name }}
      image_tag: ${{ steps.set-image.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: set-image
        run: |
          IMAGE_NAME=${{ vars.ORCHESTRATION_API_IMAGE_NAME }}
          IMAGE_TAG=${{ vars.ORCHESTRATION_API_IMAGE_TAG }}-$(date +%Y%m%d%H%M%S)
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.HIRO_KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy Helm chart
        run: |
          helm upgrade --install orchestration-api ./charts/orchestration-api \
            --namespace ${{ vars.ORCHESTRATION_API_NAMESPACE }} \
            --create-namespace \
            --set namespace=${{ vars.ORCHESTRATION_API_NAMESPACE }} \
            --set app.image.repository=${{ needs.build-and-push.outputs.image_name }} \
            --set app.image.tag=${{ needs.build-and-push.outputs.image_tag }}