name: Build and Deploy the Orchestration API

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        run: |
            docker build -t ${{ vars.ORCHESTRATION_API_IMAGE_NAME }}:${{ vars.ORCHESTRATION_API_IMAGE_TAG }} .
            docker push ${{ vars.ORCHESTRATION_API_IMAGE_NAME }}:${{ vars.ORCHESTRATION_API_IMAGE_TAG }}
            echo "IMAGE_NAME=${{ vars.ORCHESTRATION_API_IMAGE_NAME }}:${{ vars.ORCHESTRATION_API_IMAGE_TAG }}" >> $GITHUB_ENV
  
  # Enable this below job, in integration phase to deploy the application to Kubernetes
  # deploy:
  #   name: Deploy to Kubernetes
  #   runs-on: ubuntu-latest
  #   needs: update-values

  #   steps:
  #     # Step 1: Checkout the repository
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # Step 2: Set up kubectl
  #     - name: Set up kubectl
  #       uses: azure/setup-kubectl@v3
  #       with:
  #         version: 'latest'

  #     # Step 3: Set up Helm
  #     - name: Set up Helm
  #       uses: azure/setup-helm@v3
  #       with:
  #         version: 'latest'

  #     # Step 4: Deploy the Helm chart
  #     - name: Deploy Helm chart
  #       run: |
  #         helm upgrade --install orchestration-api ./charts/orchestration-api \
  #           --namespace orchestration-api \
  #           --create-namespace \
  #           --set orchestration-api.image.repository=your-dockerhub-username/orchestration-api \
  #           --set orchestration-api.image.tag=alpha1