---
# This workflow builds and deploys 
# the Orchestration API Docker image to Docker Hub
# and deploys it to a Kubernetes cluster using Helm.

name: Build and Deploy the Orchestration API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.set-repo-path.outputs.repo-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set repo path output
        id: set-repo-path
        run: echo "repo-path=${GITHUB_WORKSPACE}" >> $GITHUB_OUTPUT

  validate:
    name: Validate Python, YAML file Syntax and Testcoverage
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python files
        run: |
          pylint app/ --fail-under=${{ vars.PYLINT_EXPECTED_SCORE }}
        
      - name: Run tests with coverage
        run: pytest --cov=app --cov-fail-under=${{ vars.PYTEST_EXPECTED_PERCENTAGE }} app/tests/

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Lint Helm chart
        run: helm lint charts/orchestration-api

  test-db-migrations:
    name: Test Alembic DB Migrations
    runs-on: ubuntu-latest
    needs: validate
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orchestration_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5433 -U postgres && break
            sleep 2
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Alembic migrations
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5433/orchestration_db
        run: alembic upgrade head

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      image_name: ${{ steps.set-image.outputs.image_name }}
      image_tag: ${{ steps.set-image.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: set-image
        run: |
          IMAGE_TAG=${{ vars.ORCHESTRATION_API_IMAGE_TAG }}-$(date +%Y%m%d%H%M%S)
          docker build -t ${{ vars.ORCHESTRATION_API_IMAGE_NAME }}:$IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "image_name=${{ vars.ORCHESTRATION_API_IMAGE_NAME }}" >> $GITHUB_OUTPUT

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push ${{ vars.ORCHESTRATION_API_IMAGE_NAME }}:${{ steps.set-image.outputs.image_tag }}

  deploy:
    name: Deploy to Kubernetes
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: 
      - build-and-push
      - test-db-migrations
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.HIRO_KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Deploy Helm chart
        run: |
          helm upgrade --install orchestration-api ./charts/orchestration-api \
            --namespace ${{ vars.ORCHESTRATION_API_NAMESPACE }} \
            --create-namespace \
            --set namespace=${{ vars.ORCHESTRATION_API_NAMESPACE }} \
            --set app.image.repository=${{ vars.ORCHESTRATION_API_IMAGE_NAME }} \
            --set app.image.tag=${{ needs.build-and-push.outputs.image_tag }} \
            --set runMigration=true \
      
      - name: Wait for Alembic migration job to complete
        run: |
          # Get the latest alembic job name
          JOB_NAME=$(kubectl get jobs -n ${{ vars.ORCHESTRATION_API_NAMESPACE }} -o json \
            | jq -r '.items | map(select(.metadata.name | startswith("alembic-migration-"))) | sort_by(.metadata.creationTimestamp) | last(.[]).metadata.name')

          echo "Waiting for Job: $JOB_NAME"
          kubectl wait --for=condition=complete --timeout=300s job/$JOB_NAME -n ${{ vars.ORCHESTRATION_API_NAMESPACE }} || {
            echo "Alembic migration job failed or timed out."
            # Print job logs for debugging
            POD_NAME=$(kubectl get pods -n ${{ vars.ORCHESTRATION_API_NAMESPACE }} -l job-name=$JOB_NAME -o jsonpath="{.items[0].metadata.name}")
            kubectl logs -n ${{ vars.ORCHESTRATION_API_NAMESPACE }} $POD_NAME || true
            exit 1
          }

          # Check for job failure
          JOB_STATUS=$(kubectl get job $JOB_NAME -n ${{ vars.ORCHESTRATION_API_NAMESPACE }} -o jsonpath='{.status.failed}')
          if [[ "$JOB_STATUS" != "" && "$JOB_STATUS" != "0" ]]; then
            echo "Alembic migration job failed."
            POD_NAME=$(kubectl get pods -n ${{ vars.ORCHESTRATION_API_NAMESPACE }} -l job-name=$JOB_NAME -o jsonpath="{.items[0].metadata.name}")
            kubectl logs -n ${{ vars.ORCHESTRATION_API_NAMESPACE }} $POD_NAME || true
            exit 1
          fi