# PostgreSQL Database
postgres:
  name: postgres
  image:
    repository: postgres
    tag: "14"
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
    nodePort: 
  persistence:
    enabled: true
    size: 1Gi
  credentials:
    username: postgres
    password: postgres
    database: orchestration_db

# FastAPI Application
app:
  name: orchestration-api
  secret:
    name: orchestration-api-secret
  image:
    repository: orchestration-api
    tag: alpha1
    pullPolicy: Always
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8000
    nodePort: 

configmap:
  databaseURLConfig: orchestration-api-config
  databaseInitConfig: db-init-script

runMigration: false
namespace: orchestration-api