runMigration: false

# PostgreSQL Database
postgres:
  name: aces-postgres
  image:
    repository: postgres
    tag: "14"
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
    nodePort: 
  persistence:
    enabled: true
    size: 1Gi
  credentials:
    username: postgres
    password: postgres
    database: orchestration_db

# FastAPI Application
app:
  name: aces-orchestration-api
  secret:
    name: orchestration-api-secret
  image:
    repository: orchestration-api
    tag: alpha1
    pullPolicy: Always
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
    nodePort: 30015

configmap:
  databaseURLConfig: orchestration-api-config
  databaseInitConfig: db-init-script

# The below values are for the k8s-dashboard subchart
k8sDashboard:
  serviceAccountName: readonly-user
  reverseProxy:
    service:
      type: ClusterIP
      nodePort: 30016
  # Access URL for the Kubernetes Dashboard
  # This should be the URL where the Kubernetes Dashboard is accessible
  # If using a reverse proxy, it should point to the proxy service URL
  # For example, if using NodePort, it could be something like:
  # http://<node-ip>:<node-port>/
  # If using a LoadBalancer, it could be the external IP of the LoadBalancer
  # If using Ingress, it could be the Ingress URL
  accessURL: http://localhost:30016
