runMigration: false
namespace: aces-orchestration-api

# PostgreSQL Database
postgres:
  name: aces-postgres
  image:
    repository: postgres
    tag: "14"
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
    nodePort: 
  persistence:
    enabled: true
    size: 1Gi
  credentials:
    username: postgres
    password: postgres
    database: orchestration_db

# FastAPI Application
app:
  name: aces-orchestration-api
  secret:
    name: orchestration-api-secret
  image:
    repository: orchestration-api
    tag: alpha1
    pullPolicy: Always
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8000
    nodePort: 

configmap:
  databaseURLConfig: orchestration-api-config
  databaseInitConfig: db-init-script

dashboard:
  # Namespace should match the value set in the 
  # k8s-dashboard chart (values.namespace)
  namespace: kubernetes-dashboard 
  # Service account name should match the value set in the 
  # k8s-dashboard chart (values.serviceAccountName)
  serviceAccountName: readonly-user
  # Reverse proxy service name should match the value set in the 
  # k8s-dashboard chart (values.reverseProxy.Name)  
  reverseProxyServiceName: aces-dashboard-reverse-proxy
  # Reverse proxy service port should match the value set in the 
  # k8s-dashboard chart (values.reverseProxy.service.port)  
  reverseProxyServicePort: 80
